# Generated by Django 5.0.1 on 2024-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
