# Generated by Django 5.0.1 on 2024-01-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0002_genre_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
