# Generated by Django 5.0.1 on 2024-01-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0003_alter_genre_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
