# Generated by Django 5.0.1 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0005_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/books/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN книги'),
        ),
    ]
