# Generated by Django 4.2 on 2024-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0013_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000, verbose_name='Комментарий'),
        ),
    ]
