# Generated by Django 4.2 on 2024-04-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0015_alter_books_files_alter_books_image_bookcountviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='recommended_books',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
