# Generated by Django 4.2 on 2024-04-18 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAsia_blog', '0017_like_dislikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='Dislike',
        ),
    ]
