# Generated by Django 4.2 on 2024-04-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAsia_blog', '0018_rename_dislikes_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='myAsia_blog.books'),
        ),
        migrations.AlterField(
            model_name='like',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myAsia_blog.books'),
        ),
    ]
